# -*- coding: utf-8 -*-
"""trafficsigns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfyMtxvK11sbuC_UMVIT6wqhCW4g8xN3
"""

!pip install kaggle
!pip install keras
import kagglehub
path = kagglehub.dataset_download("meowmeowmeowmeowmeow/gtsrb-german-traffic-sign")
print(path)
import tensorflow as tf
from keras.layers import Flatten, Dense, Dropout, Conv2D, MaxPool2D
from keras.applications import VGG16
import numpy as np
import matplotlib.pyplot as plt
import os
from keras.utils import to_categorical
from keras.models import Sequential
from PIL import Image

all_imgs_path = "/kaggle/input/gtsrb-german-traffic-sign/Train"
imgdata=[]
labels = []
numclass = 43
for i in range (numclass):
  img_path = all_imgs_path + "/"+str(i)
  for t in  os.listdir(img_path): #listdir connects directories in form of list
    opened = Image.open(img_path + "/" + t)
    opened= opened.resize((30,30))
    opened = np.array(opened)
    imgdata.append(opened)
    labels.append(i)

imgdata = np.array(imgdata)
labels.np.array(labels)

print(labels)
imgdata